#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-gem_hadar
Version  : 1.2.1
Release  : 7
URL      : https://rubygems.org/downloads/gem_hadar-1.2.1.gem
Source0  : https://rubygems.org/downloads/gem_hadar-1.2.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-gem_hadar
BuildRequires : rubygem-rdoc

%description


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n gem_hadar-1.2.1
gem spec %{SOURCE0} -l --ruby > rubygem-gem_hadar.gemspec

%build
gem build rubygem-gem_hadar.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
gem_hadar-1.2.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/gem_hadar-1.2.1.gem
/usr/lib64/ruby/gems/2.3.0/gems/gem_hadar-1.2.1/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/gem_hadar-1.2.1/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/gem_hadar-1.2.1/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/gem_hadar-1.2.1/README.md
/usr/lib64/ruby/gems/2.3.0/gems/gem_hadar-1.2.1/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/gem_hadar-1.2.1/VERSION
/usr/lib64/ruby/gems/2.3.0/gems/gem_hadar-1.2.1/gem_hadar.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/gem_hadar-1.2.1/lib/gem_hadar.rb
/usr/lib64/ruby/gems/2.3.0/gems/gem_hadar-1.2.1/lib/gem_hadar/version.rb
/usr/lib64/ruby/gems/2.3.0/specifications/gem_hadar-1.2.1.gemspec
